example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import add_task_ajax, show_todolist, register, login_user, logout_user, add_task, change_status, delete_task, show_todolist_ajax, show_todolist_json

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', add_task, name='add_task'),
    path('change-status/', change_status, name='change_status'),
    path('delete-task/', delete_task, name='delete_task'),
    # Tugas 6 : AJAX
    path('json/', show_todolist_json, name='show_todolist_json'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
    path('add/', add_task_ajax, name='add_task_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.TextField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from multiprocessing import context
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Alifia Nadiya Putri',
        'npm': '2106708002',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    data_mywatchlist = MyWatchList.objects.all()
    count_watched = 0
    for title in data_mywatchlist:
        if(title.watched=="Yes"):
            count_watched+=1
    if(count_watched > 10 - count_watched):
        pesan = "Selamat, kamu sudah banyak menonton!"
    else:
        pesan  = "Wah, kamu masih sedikit menonton!"
    context = {
        'list_watch': data_mywatchlist,
        'nama': 'Alifia Nadiya Putri',
        'npm': '2106708002',
        'pesan': pesan
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render, redirect
from todolist.models import Task
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from todolist.forms import TaskForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from datetime import datetime

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = Task.objects.filter(user=request.user)
    context = {
        'list_todo': data_todolist,
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def add_task(request):
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.user=User.objects.get(username=request.user.username)
            data.save()
            return redirect('todolist:show_todolist')

    context = {'form':form}
    return render(request, 'addtask.html', context)

def change_status(request):
    if request.method == "POST":
        task = Task.objects.get(id=request.POST["id"])
        task.is_finished = not(task.is_finished)
        task.save()
    return redirect('todolist:show_todolist')

def delete_task(request):
    if request.method == "POST":
        task = Task.objects.get(id=request.POST["id"])
        task.delete()
    return redirect('todolist:show_todolist')

#Tugas 6: AJAX 

@login_required(login_url='/todolist/login/')
def show_todolist_json(request):
    data_todolist = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data_todolist), content_type="application/json")

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    return render(request, "todolist_ajax.html")

@login_required(login_url='/todolist/login/')
def add_task_ajax(request):
    if request.method == 'POST':
        titleBaru = request.POST.get('title')
        descBaru = request.POST.get('description')
        new_task = Task(
            user = request.user,
            date = datetime.now(),
            title = titleBaru,
            description = descBaru,
            is_finished = False,
        )
        new_task.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
          <th>{{barang.item_name}}</th>
          <th>{{barang.item_price}}</th>
          <th>{{barang.item_stock}}</th>
          <th>{{barang.rating}}</th>
          <th>{{barang.description}}</th>
          <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 2 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for watch in list_watch %}
      <tr>
          <th>{{watch.watched}}</th>
          <th>{{watch.title}}</th>
          <th>{{watch.rating}}</th>
          <th>{{watch.release_date}}</th>
          <th>{{watch.review}}</th>
      </tr>
    {% endfor %}
  </table>

  <p>{{pesan}}</p>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/addtask.html
{% extends 'base.html' %}

{% block meta %}
<title>Tambah Task</title>
{% endblock meta %}

{% block content %}
<header>
    <h1>Tambah Task</h1>  
</header>

<div class = "add_task">
    <form method="POST">  
        {% csrf_token %}  
        <table>
            {{ form.as_table }}
            
        </table>
        <input type="submit" class="btn btn-primary" name="submit" value="Tambah Task"/>
    </form>
</div>  

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<header>
    <h1>Login</h1>
</header>

<div class = "login">
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>

        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <p>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></p>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %} 
<header>
    <h1>Formulir Registrasi</h1>  
</header> 

<div class = "register">
        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
            </table>  
            <input type="submit" class="btn btn-primary" name="submit" value="Daftar"/>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
<header>
  <h1>To Do List</h1>

  <h2>User: {{ user }}</h2>
</header>

<div class="card-deck">
  {% for data in list_todo %}
  <div class="card">
    <div class="card-body">
      <h3>{{data.title}}</h3>
      <h6>{{data.description}}</h6>

      {% if data.is_finished %}
          <p><b>Selesai</b></p>
      {% else %}
          <p><b>Belum Selesai</b></p>
      {% endif %}

      <div class="container-button">
        <div class="button-ganti-status">
          <form method="POST" action="{% url 'todolist:change_status' %}">
            {% csrf_token %} 
            <input type="hidden" name="id" value="{{ data.id }}">
            <button type="submit" class="btn btn-warning">Ganti Status</button>
          </form>
        </div>
        
        <div class="button-hapus-task">
          <form method="POST" action="{% url 'todolist:delete_task' %}">
            {% csrf_token %} 
            <input type="hidden" name="id" value="{{ data.id }}">
            <button type="submit" class="btn btn-danger">Hapus Task</button>
          </form>
        </div>
      </div>

    </div>

    <div class="card-footer">
      <p class="task-date">{{data.date}}</p>
    </div>
  </div>
  {% endfor %}
</div>

<!-- <table>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Change Status</th>
      <th>Delete Task</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for data in list_todo %}
    <tr>
        <th>{{data.date}}</th>
        <th>{{data.title}}</th>
        <th>{{data.description}}</th>

        {% if data.is_finished %}
        <th>Selesai</th>
        {% else %}
        <th>Belum Selesai</th>
        {% endif %}

        <th>
          <form method="POST" action="{% url 'todolist:change_status' %}">
            {% csrf_token %} 
            <input type="hidden" name="id" value="{{ data.id }}">
            <button type="submit">Ganti Status</button>

          </form>
        
        </th>

        <th>
          <form method="POST" action="{% url 'todolist:delete_task' %}">
            {% csrf_token %} 
            <input type="hidden" name="id" value="{{ data.id }}">
            <button type="submit">Hapus Task</button>

          </form>
        
        </th>

    </tr>
    {% endfor %}
</table> -->

<footer>
  <a type="button" class="btn btn-light" href="{% url 'todolist:add_task' %}">Tambah Task Baru</a>
  <a type="button" class="btn btn-light" href="{% url 'todolist:logout' %}">Logout</a>
</footer>

{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block content %}
<header>
  <h1>To Do List</h1>

  <h2>User: {{ user }}</h2>
</header>

<table id="table"></table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    async function loadTable(){
        document.getElementById("table").innerHTML = ""
        let htmlString = `<tr>
            <th>Date</th>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
        </tr>`
        $.get("{% url 'todolist:show_todolist_json' %}", function(data){
            for(var i = 0; i < data.length; i++){
                var status = ""

                if (data[i].fields.is_finished){
                    status = "Selesai"
                }
                else {
                    status = "Belum Selesai"
                }

                htmlString += `\n<tr>
                    <th>${data[i].fields.date}</th>
                    <th>${data[i].fields.title}</th>
                    <th>${data[i].fields.description}</th>
                    <th>${status}</th>
                </tr>`
            }
            document.getElementById("table").innerHTML = htmlString
        })        
    }

    $(document).on('submit', '#form_add', function(e) {
        e.preventDefault()
        loadTable()
        $.ajax({
            type:"POST",
            url:"{% url 'todolist:add_task_ajax' %}",
            data:{
                date:$("#date").val(),
                title:$("#title").val(),
                description:$("#description").val(),
                is_finished:$("#is_finished").val(),
                csrfmiddlewaretoken:'{{ csrf_token }}',
            },
            dataType: 'json',
        })
        document.getElementById("form_add").reset()
        loadTable()
    })

    loadTable()
</script>

<footer>
    <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Tambah Task</button>
  <a type="button" class="btn btn-light" href="{% url 'todolist:logout' %}">Logout</a>
</footer>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Task Baru</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
        <!-- Isi Form -->
        <form id="form_add" method="POST" action="">
            <div class="modal-body">
                    <p>Title</p>
                    <p><input id="title" type="text" name="title" placeholder="Title" class="form-control"></p>
                    <p>Description</p>
                    <p><input id="description" type="text" name="description" placeholder="Description" class="form-control"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" data-bs-dismiss="modal" class="btn btn-primary">Tambah Task</button>
            </div>
        </form>
    </div>
</div>
</div>

<style>
    table, td, th {
      border: 1px solid;
    }
</style>
{% endblock content %}